### ISSUE TITLE
Wrong description in TER / marked as abandoned

### ISSUE THREAD

**Issue by peterkraume** [dr-blitz-weblab/phone#1]
In TER your freshly uploaded extension has the wrong title and description. Furthermore your extension is marked as abandoned.

If you need support for changing that please visit the TYPO3 Slack channel #t3o-ter-team

![Screenshot_2024-01-15_07 52 19](https://github.com/dr-blitz-weblab/phone/assets/4234704/cf74982f-3957-48e0-92b2-25f189f522bd)

**Comment by nadziejawnas** [comment]
Solved by version 2.0.1

**Comment by drblitz-weblab** [comment]
solved
